# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.7 on 2016-08-11 22:55
=======
# Generated by Django 1.9.7 on 2016-08-11 20:59
>>>>>>> b4bc69b5a1006d178a330f54f091b1877f29ad37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorinfo',
            name='lnglat',
        ),
    ]
