# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 08:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid_By_Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='멘티')),
            ],
        ),
        migrations.CreateModel(
            name='Bid_By_Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.TextField(verbose_name='멘토링 커리큘럼')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='멘토')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300, verbose_name='댓글 내용')),
                ('secret', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matched_Bid_By_Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor', models.CharField(max_length=20, verbose_name='멘토 이름')),
                ('mentee', models.CharField(max_length=20, verbose_name='멘티 이름')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.Bid_By_Mentee')),
            ],
        ),
        migrations.CreateModel(
            name='Matched_Bid_By_Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor', models.CharField(max_length=20, verbose_name='멘토 이름')),
                ('mentee', models.CharField(max_length=20, verbose_name='멘티 이름')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.Bid_By_Mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Post_By_Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('남', '남'), ('여', '여')], default='', max_length=20, verbose_name='원하는 멘토 성별')),
                ('lnglat', models.CharField(max_length=20, verbose_name='멘티 위치')),
                ('major', models.CharField(choices=[('간호대학', '간호대학'), ('건축학과', '건축학과'), ('경영대학', '경영대학'), ('농경제사회학부', '농경제사회학부'), ('사회과학계열', '사회과학계열'), ('심리학과', '심리학과'), ('소비자아동학부', '소비자아동학부'), ('의류학과', '의류학과'), ('인문계열', '인문계열'), ('언어학과', '언어학과'), ('교육학과', '교육학과'), ('국어교육과', '국어교육과'), ('물리교육과', '물리교육과'), ('사회교육과', '사회교육과'), ('생물교육과', '생물교육과'), ('역사교육과', '역사교육과'), ('영어교육과', '영어교육과'), ('지구과학교육과', '지구과학교육과'), ('지리교육과', '지리교육과'), ('체육교육과', '체육교육과'), ('화학교육과', '화학교육과'), ('수학교육과', '수학교육과'), ('물리천문학부', '물리천문학부'), ('바이오시스템소재학부', '바이오시스템소재학'), ('산림과학부', '산림과학부'), ('생명과학부', '생명과학부'), ('수리과학부', '수리과학부'), ('식물생산과학부', '식물생산과학부'), ('식품영양학과', '식품영양학과'), ('응용생물화학부', '응용생물화학부'), ('화학부', '화학부'), ('건설환경공학부', '건설환경공학부'), ('기계항공공학부', '기계항공공학부'), ('산업공학과', '산업공학과'), ('식품동물생명공학부', '식품동물생명공학부'), ('재료공학부', '재료공학부'), ('전기정보공학부', '전기정보공학부'), ('조경지역시스템공학부', '조경지역시스템공학부'), ('조선해양공학과', '조선해양공학과'), ('컴퓨터공학부', '컴퓨터공학부'), ('화학생물공학부', '화학생물공학부'), ('의예과', '의예과')], default='', max_length=20, verbose_name='전공')),
                ('grade', models.CharField(choices=[('1학년', '1학년'), ('2학년', '2학년'), ('3학년', '3학년'), ('4학년 이상', '4학년 이상')], default='', max_length=40, verbose_name='학년')),
                ('GPA', models.CharField(choices=[('아주 높은 편', '아주 높은 편'), ('높은 편', '높은 편'), ('중간 정도', '중간 정도'), ('낮은 편', '낮은 편'), ('아주 낮은 편', '아주 낮은 편')], default='', max_length=40, verbose_name='성취도')),
                ('hours', models.IntegerField(default=0, verbose_name='멘토링 진행시간')),
                ('date', models.DateTimeField(verbose_name='멘토링 날짜')),
                ('price', models.IntegerField(default=0, verbose_name='희망 수업료')),
                ('intro', models.TextField(max_length=300, verbose_name='기타 소개')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post_By_Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity', models.IntegerField(default=0, verbose_name='멘토링 인원')),
                ('hours', models.IntegerField(default=0, verbose_name='멘토링 시간')),
                ('date', models.DateTimeField(max_length=50, verbose_name='멘토링 날짜')),
                ('lowest_price', models.IntegerField(default=0, verbose_name='최저 멘토링비')),
                ('like_count', models.IntegerField(default=0, verbose_name='좋아요 수')),
                ('intro', models.TextField(max_length=300, verbose_name='기타 소개')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='like_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.Post_By_Mentor'),
        ),
        migrations.AddField(
            model_name='like',
            name='like_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.Post_By_Mentor'),
        ),
        migrations.AddField(
            model_name='bid_by_mentor',
            name='post_by_mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.Post_By_Mentee'),
        ),
        migrations.AddField(
            model_name='bid_by_mentee',
            name='post_by_mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.Post_By_Mentor'),
        ),
    ]
