# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0002_auto_20160810_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_by_mentor',
            name='photo1',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post_by_mentor',
            name='photo2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post_by_mentor',
            name='photo3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
