# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0004_auto_20160812_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_by_mentee',
            name='date',
            field=models.DateTimeField(default='yyyy-mm-dd 형식으로 써주세요.', verbose_name='멘토링 날짜'),
        ),
    ]
