# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0005_auto_20160812_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_by_mentee',
            name='lnglat',
        ),
    ]
